apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: iam-storage
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: iam-project

  source:
    repoURL: {{ $.Values.gitRepositoryUrl }}
    targetRevision: {{ $.Values.targetRevision }}
    path: iam-storage

  destination:
    server: https://kubernetes.default.svc
    namespace: {{ $.Values.iam.namespace }}

  syncPolicy:
    automated:
      prune: false
      selfHeal: true
      allowEmpty: true
    syncOptions:
    - Validate=true
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground 
    - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 30s
        factor: 2
        maxDuration: 3m
