apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rook-ceph
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: storage-project

  source:
    repoURL: {{ $.Values.rookCeph.helmUrl }}
    targetRevision: v1.8.3
    chart: rook-ceph

  destination:
    server: https://kubernetes.default.svc
    namespace: {{ $.Values.rookCeph.namespace }}

  syncPolicy:
    automated: 
      prune: false
      selfHeal: true
      allowEmpty: false
    syncOptions:
    - Validate=true
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 30s
        factor: 2
        maxDuration: 3m
