
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: storage-ceph-cluster
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: storage-project

  source:
    repoURL: {{ $.Values.gitRepositoryUrl }}
    targetRevision: {{ $.Values.targetRevision }}
    path: storage-apps/storage-ceph-cluster
    
    helm:
      parameters:
      - name: cloudProvider.storageClass
        value: {{ $.Values.cloudProvider.storageClass }}
      - name: rookCeph.namespace
        value: {{ .Values.rookCeph.namespace }}

  destination:
    server: https://kubernetes.default.svc
    namespace: {{ $.Values.rookCeph.namespace }}

  syncPolicy:
    automated: 
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
    - Validate=true
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 30s
        factor: 2
        maxDuration: 3m